import type { Metadata } from "next";
import SideNav from "./Components/SideNav";
import Navbar from "@/app/components/Navbar";
import Ads from "./Components/Ads";

import { GeistSans } from "geist/font/sans";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "@/components/ui/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>

          <div className="flex mx-auto h-full max-w-[1390px]">
            <SideNav />
            <div className="w-full ml-10 mr-24 mt-8 max-md:ml-3 max-md:mr-0">{children}</div>
          </div>
       
      </body>
    </html>
  );
}
