import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import SideNav from "./Components/SideNav";
import Navbar from "@/app/components/Navbar";

export const metadata: Metadata = {
  title: "CSS ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Navbar />
        <div className="flex mx-auto h-full max-w-[1390px] pt-8 border-l border-r max-lg:border-none">
          <SideNav />
          <div className="w-full ml-10  max-lg:ml-3 max-lg:mr-2 max-h-[80vh]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
