import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";
import SideNav from "./Components/SideNav";

export const metadata: Metadata = {
  title: "CSS ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <div className="flex mx-auto h-full max-w-[1390px]">
          <SideNav />
          <div className="w-full ml-10 mr-24 mt-8 max-lg:ml-3 max-lg:mr-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
